
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HOLA COMA QUE TAL\n    ForS : ForX QUE TAL\n    \n       ForX : HOLA\n            | ForX COMA HOLA\n     '
    
_lr_action_items = {'HOLA':([0,5,],[3,7,]),'$end':([1,6,],[0,-1,]),'QUE':([2,3,7,],[4,-2,-3,]),'COMA':([2,3,7,],[5,-2,-3,]),'TAL':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ForS':([0,],[1,]),'ForX':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ForS","S'",1,None,None,None),
  ('ForS -> ForX QUE TAL','ForS',3,'p_ForS','parseronefile.py',36),
  ('ForX -> HOLA','ForX',1,'p_ForX','parseronefile.py',40),
  ('ForX -> ForX COMA HOLA','ForX',3,'p_ForX','parseronefile.py',41),
]
